#
# product notes for Kyverno: (TODO file issues or something?)
#
# - index.docker.io is not and has not been canonical for 8+ years - that should be normalized to "docker.io"
# - that "allImages" variable should be automatic somehow because otherwise every ImageValidatingPolicy has to duplicate it (and extend it over time as new "containers" type objects get added to the relevant k8s specs)
# - traversing image indexes automatically and validating *all* entries should be an automatic / high-level supported thing (otherwise doing things like validating "config" properties is less secure than it should be because it'll only validate linux/amd64 and linux/arm64 might not pass the policy AND might be the image actually deployed by kubelet)
# - as written, this assumes *all* image references will be "image indexes" and it's actually kind of difficult to make it generic and have it work for non-indexes too - relevent to the above, there should be an easy way to do that (essentially to have an ImageValidatingPolicy that validates every "image manifest" that's part of *any* image reference in the k8s spec)
# - "matchImageReferences" is only applied *during* the call to "verifyImageSignatures", so this implementation ends up doing registry lookups for *every* image only to throw some of them away when they don't match (and increases the chances of hitting registry rate limits)
# - documentation for "attestors.cosign.source" incorrectly claims it's a filter, when it's where to look up the signatures from
# - the "disable ctlog" functionality leaves a lot to be desired
#   - the "ignore" flags are implemented as "perform the validation but then ignore the result" which is wild
#   - as a side effect, specifying ignore only works if the URL is specified explicitly also (which then slows down the verification unless the URL is obviously invalid and thus fails before performing *any* validation)
#   - the "TUF" parts still happen, even though they don't need to / shouldn't (wasting time and resources)
# - when writing a complex CEL expression like this one, there's no way I can find to "raise" a better error message on policy failure (so that it can be specific about what/where it failed, for example) - it's just strictly pass or fail
#   - related, the debugging/development experience is pretty poor - if something fails, it's hard to figure out why (no feedback loop)
# - cosign signatures are signatures of a "payload" JSON object that has a bunch of interesting properties (and an infinite number of optional user-specified properties) - it would be really helpful if the policy could access those somehow to validate them too, after validating the signature
#   - see https://oci.dag.dev/?blob=tianon/referrers@sha256:d6d92cd099663f2136b56525de46efc7ea99b2f8b468b458349e3bf4cf92ff99&mt=application%2Fvnd.dev.cosign.simplesigning.v1%2Bjson&size=1297 for an example
# - support for cosign signatures via referrers ("experimental OCI 1.1 support" as cosign calls it)

apiVersion: policies.kyverno.io/v1alpha1
kind: ImageValidatingPolicy
metadata:
  name: example-doi-policy
spec:
  matchImageReferences:
    # ideally we'd not have this extra star at the start and just use "docker.io/library/*" but Kyverno is a little confused and normalizes docker.io to "index.docker.io" instead which hasn't been correct/canonical for at least 8 years 🙈
    - glob: "*docker.io/tianon/*"
  attestors:
    - name: cosignTianon
      cosign:
        source:
          repository: tianon/referrers
        key:
          data: |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECMVnSOJPIb1BXkEn6Y9ni2+ZMVVa
            /vcQmVUl4YwN6qoJPu0zGi100HVIzi44f4nt5xbVnDQTzlXjw8R0mOGL0A==
            -----END PUBLIC KEY-----
        ctlog:
          insecureIgnoreTlog: true
          insecureIgnoreSCT: true
          # there's a nasty little bug in Kyverno where it assumes that if this object has contents, that they specify an alternate server, even though the flags for "don't Rekor at all" live inside this object too 😞
          # https://github.com/kyverno/kyverno/blob/b9e2c3f77d6de1d9e19dd5837d1b610fa9483d0c/pkg/imageverification/imageverifiers/cosign/opts.go#L217
          # so, we have to specify a rekor URL that will get queried and then the results of ignored, because that's how the Kyverno implementation works
          # in fact, the image verifications happen *faster* if this value is invalid because the Rekor validation fails faster (and then the failure gets ignored)
          url: https://this.is.a.totally.bogus.domain.that.should.not.exist/
  variables:
    - name: allImages
      expression: |
        images.containers
        + images.?initContainers.orValue([])
        + images.?ephemeralContainers.orValue([])
  validations:
    - expression: |
        variables.allImages.all(ref,
          [ image(ref) ].all(img,
            [ image.GetMetadata(ref) ].all(meta,
              meta.imageIndex.manifests.filter(desc,
                desc.platform.os == "linux" // windows images and buildkit attestations are not (currently) signed
              ).all(desc,
                verifyImageSignatures(
                  img.registry() + "/" + img.repository() + "@" + desc.digest,
                  [ attestors.cosignTianon ]
                ) > 0
                // TODO find some way to raise *which* image fails, because this is otherwise just pass/fail on the entire k8s pod spec 😭
              )
            )
          )
        )
